import fs from "fs/promises";
import path from "path";
import { getDb, throwIfMatuError, pickRow } from "../db/matu.js";
import { env } from "../config/env.js";
import type { NginxVhost } from "../types/index.js";
import { NotFoundError } from "../utils/errors.js";
import * as hostingService from "./hosting.service.js";
import { ensureDefaultSite } from "../utils/default-site.js";

function buildNginxConfig(serverName: string, documentRoot: string): string {
  const www = serverName.startsWith("www.") ? serverName : `www.${serverName}`;
  return `# Generated by MatuHost — ${new Date().toISOString()}
server {
    listen 80;
    listen [::]:80;
    server_name ${serverName} ${www};

    root ${documentRoot.replace(/\\/g, "/")};
    index index.html index.htm;

    access_log /var/log/nginx/${serverName}-access.log;
    error_log /var/log/nginx/${serverName}-error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\\. {
        deny all;
    }
}
`;
}

export async function listVhosts(userId: string): Promise<NginxVhost[]> {
  const { data, error } = await getDb()
    .from("nginx_vhosts")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  throwIfMatuError(error);
  return (data ?? []) as NginxVhost[];
}

export async function getVhost(userId: string, id: string): Promise<NginxVhost> {
  const { data, error } = await getDb()
    .from("nginx_vhosts")
    .select("*")
    .eq("id", id)
    .eq("user_id", userId)
    .single();

  throwIfMatuError(error, "Nginx vhost not found");
  if (!data) throw new NotFoundError("Nginx vhost not found");
  return data as NginxVhost;
}

export async function createVhost(
  userId: string,
  data: { server_name: string; hosting_account_id?: string; domain_id?: string }
): Promise<NginxVhost> {
  let documentRoot = path.join(env.DEFAULT_DOCUMENT_ROOT, data.server_name, "public_html");

  if (data.hosting_account_id) {
    const hosting = await hostingService.getHosting(userId, data.hosting_account_id);
    documentRoot = hosting.document_root;
  } else if (data.domain_id) {
    const { data: row, error } = await getDb()
      .from("domains")
      .select("fqdn")
      .eq("id", data.domain_id)
      .eq("user_id", userId)
      .single();
    throwIfMatuError(error, "Domain not found");
    if (!row) throw new NotFoundError("Domain not found");
    documentRoot = await ensureDefaultSite((row as { fqdn: string }).fqdn);
  }

  const configFileName = `${data.server_name.replace(/\./g, "_")}.conf`;
  const configPath = path.join(env.NGINX_VHOSTS_DIR, configFileName);

  await fs.mkdir(env.NGINX_VHOSTS_DIR, { recursive: true });
  await fs.mkdir(path.dirname(documentRoot), { recursive: true });

  const config = buildNginxConfig(data.server_name, documentRoot);
  await fs.writeFile(configPath, config, "utf-8");

  const { data: inserted, error } = await getDb().from("nginx_vhosts").insert({
    user_id: userId,
    domain_id: data.domain_id ?? null,
    hosting_account_id: data.hosting_account_id ?? null,
    server_name: data.server_name,
    config_path: configPath,
    status: "generated",
  });

  throwIfMatuError(error);
  return pickRow<NginxVhost>(inserted);
}

export async function enableVhost(userId: string, id: string): Promise<NginxVhost> {
  const vhost = await getVhost(userId, id);
  const enabledPath = path.join(env.NGINX_SITES_ENABLED_DIR, path.basename(vhost.config_path));

  await fs.mkdir(env.NGINX_SITES_ENABLED_DIR, { recursive: true });
  const config = await fs.readFile(vhost.config_path, "utf-8");
  await fs.writeFile(enabledPath, config, "utf-8");

  const { data: rows, error } = await getDb()
    .from("nginx_vhosts")
    .eq("id", id)
    .update({
      enabled: true,
      status: "enabled",
      updated_at: new Date().toISOString(),
    });

  throwIfMatuError(error);
  return pickRow<NginxVhost>(rows);
}

export async function disableVhost(userId: string, id: string): Promise<NginxVhost> {
  const vhost = await getVhost(userId, id);
  const enabledPath = path.join(env.NGINX_SITES_ENABLED_DIR, path.basename(vhost.config_path));

  try {
    await fs.unlink(enabledPath);
  } catch {
    /* ignore */
  }

  const { data: rows, error } = await getDb()
    .from("nginx_vhosts")
    .eq("id", id)
    .update({
      enabled: false,
      status: "disabled",
      updated_at: new Date().toISOString(),
    });

  throwIfMatuError(error);
  return pickRow<NginxVhost>(rows);
}

export async function deleteVhost(userId: string, id: string): Promise<void> {
  const vhost = await getVhost(userId, id);
  try {
    await fs.unlink(vhost.config_path);
  } catch {
    /* ignore */
  }
  const { error } = await getDb().from("nginx_vhosts").eq("id", id).eq("user_id", userId).delete();
  throwIfMatuError(error);
}
